### ISSUE TITLE
Question about placement of extra actions

### ISSUE THREAD

**Issue by ZarestiaDev** [Morturg/FG-Extra-Actions#7]
How would you feel about placing your in the charsheet/overview windowclass instead in the actions? Then the extra actions would be visible on every tab (and impact with other extensions would probably be less).

**Comment by Morturg** [comment]
absolutely sounds like a cracking idea, I can take a look at the weekend :-D

unless you have something you want to push!

I'm just usually very slow :D

**Comment by ZarestiaDev** [comment]
I can do a push later today or tomorrow. I've done similiar things before so I know where to change things.

**Comment by Morturg** [comment]
sorry took ages to come back to this pushed it forward now :)
